//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class altyorum
    {
        public int altyorumid { get; set; }
        public int altyorumuser { get; set; }
        public int altyorumustid { get; set; }
        public string altyorummetin { get; set; }
        public int altyorumpuan { get; set; }
        public System.DateTime altyorumtarih { get; set; }
        public int altyorumonay { get; set; }
    }
}
