//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userlar> userlar { get; set; }
        public virtual DbSet<roller> roller { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<yorumlar> yorumlar { get; set; }
        public virtual DbSet<sepette> sepette { get; set; }
        public virtual DbSet<altyorum> altyorum { get; set; }
    }
}
