//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepette
    {
        public int sepetid { get; set; }
        public int suserid { get; set; }
        public int surunid { get; set; }
        public int sadet { get; set; }
    }
}
