//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int urunid { get; set; }
        public string urunad { get; set; }
        public decimal urunfiyat { get; set; }
        public string urunresim { get; set; }
        public int urunkateg { get; set; }
        public int urunpuan { get; set; }
        public int urunindirim { get; set; }
    }
}
