//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorumlar
    {
        public int yorumid { get; set; }
        public int yorumuser { get; set; }
        public int yorumurun { get; set; }
        public string yorummetin { get; set; }
        public int yorumpuan { get; set; }
        public int yorumonay { get; set; }
        public System.DateTime yorumtarih { get; set; }
    }
}
